package com.comtrade.domen;

public enum KonstanteKPL {

    LOGOVANJE,VRATI_PODATKE_KORISNIK,UNOS_PODATAKA_KORISNIK,IZMENA_IMENA_KORISNIKA,OBRISI_KORISNIKA,VRATI_ID_KORISNIK, VRATI_IME_KORISNIKA,

    VRATI_PODATKE, UNOS_PODATAKA, OBRISI_POZORISTE, IZMENA_PODATAKA_O_POZORISTU, IMENA_POZORISTA, VRATI_ID_POZORISTA, VRATI_NAZIV_POZORISTA,

    VRATI_IMENA_KOLONA_PREDSTAVE, VRATI_PODATKE_PREDSTAVA, UNOS_PODATAKA_PREDSTAVA, OBRISI_PREDSTAVU, IZMENA_IMENA_PREDSTAVE, IMENA_PREDSTAVA,
    VRATI_ID_PREDSTAVE, VRATI_NAZIV_PREDSTAVE,

    VRATI_PODATKE_TERMINI, UNOS_PODATAKA_TERMINI, IZMENA_TERMINA, IZBRISI_TERMIN, VRATI_ID_TERMINA, VRATI_PODATKE_TERMINI_VREMENA,
    VRATI_PODATKE_TERMINI_TERMINI,

    REZERVACIJA_BROJ_ULAZNICA, UNESI_REZERVACIJE, REZERVACIJA_PREGLED_REZERVACIJA,

    VRATI_PODATKE_ULAZNA_STRANA,

    VRATI_PODATKE_GLUMAC, VRATI_GLUMCE_U_PREDSTAVI, UPISI_GLUMCA, VRATI_ID_GLUMCA, UPIS_GLUMAC_PREDSTAVA, OBRISI_GLUMCA
}
